### ISSUE TITLE
Getting error starting the app

### ISSUE THREAD

**Issue by giggioz** [elvismercado/meteor-raix-push-demo#2]
I have a long error message on my console when i run the meteor command to start the app, any idea?

Thanks

giggioz@MacGiggioz:~/Spaghetti/meteor-raix-push-demo$ meteor
[[[[[ ~/Spaghetti/meteor-raix-push-demo ]]]]] 

=> Started proxy.  
=> A patch (Meteor 1.0.3.2) for your current release is available!
   Update this project now with 'meteor update --patch'.
Push configuration, Error: Unexpected token / SyntaxError: Unexpected token /
    at Object.parse (native)
    at Package (packages/configuration/plugin/push.configuration.js:147:1)
    at **bottom_mark** (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/parse-stack.js:92:14)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:739:43
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at compileUnibuild (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:325:5)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:135:26
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compiler.compile (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:131:5)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:2023:24
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.exports.bundle (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1975:31)
    at bundleApp (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:508:34)
    at [object Object]._.extend._runOnce (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:544:35)
    at [object Object]._.extend._fiber (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:771:28)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:366:12
Push configuration, Error: Unexpected token / SyntaxError: Unexpected token /
    at Object.parse (native)
    at Package (packages/configuration/plugin/push.configuration.js:147:1)
    at __bottom_mark__ (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/parse-stack.js:92:14)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:739:43
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at compileUnibuild (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:325:5)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:135:26
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.compiler.compile (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:131:5)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:2023:24
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:264:13
    at [object Object]._.extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:257:29
    at [object Object]._.extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:255:18
    at [object Object]._.extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:246:23
    at [object Object]._.extend.withValue (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/fiber-helpers.js:115:14)
    at Object.capture (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/buildmessage.js:245:19)
    at Object.exports.bundle (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/bundler.js:1975:31)
    at bundleApp (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:508:34)
    at [object Object]._.extend._runOnce (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:544:35)
    at [object Object]._.extend._fiber (/Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:771:28)
    at /Users/giggioz/.meteor/packages/meteor-tool/.1.0.40.e5ymkv++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-app.js:366:12

**Comment by KristerV** [comment]
me too. doesn't work with `meteor update` either. This this is useless.

**Comment by cacheflow** [comment]
I think I figured this error out. It has to do with the JSON file. If you start up the app as is without inserting your own credentials and removing the comment on line 14, then you'll receive the above error because JSON is trying to read the comment. 

I got rid of it by inserting my APN credentials and deleting the comment on line 14.

**Comment by elvismercado** [comment]
yes. you have to use the correct paths in your json file. Have you tried to use the dev branch yet?
